# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
base = "/"
publish = "build/"
command = "PUBLIC_BUILD_TIMESTAMP_UTC=$(date -u +%FT%TZ) npm run build"

[build.environment]
NODE_VERSION = "20.20.2"

# let's test this
# [build.processing]
# bundle = true
# minify = true

[[redirects]]
from = "/cv"
to = "https://drive.google.com/file/d/1pGKRrs6UCesvZulALOYSpMilfb0njTHL/view?usp=sharing"
status = 302
force = true

[[redirects]]
from = "/resume"
to = "https://drive.google.com/file/d/1pGKRrs6UCesvZulALOYSpMilfb0njTHL/view?usp=sharing"
status = 302
force = true

[[redirects]]
from = "/spiderman"
to = "https://qirh.github.io/spider-man-game/"
status = 302
force = true

[[redirects]]
from = "/spider-man"
to = "https://qirh.github.io/spider-man-game/"
status = 302
force = true

[[redirects]]
from = "/address"
to = "https://qirh.github.io/address/"
status = 302
force = true

[[redirects]]
from = "/sunnyside"
to = "https://sunnysideshines.org/events/sunnysiderestaurantweek2026/"
status = 302
force = true

[[redirects]]
from = "/blog"
to = "https://saleh.soy/"
status = 302
force = true

[[redirects]]
from = "/posts"
to = "https://saleh.soy/"
status = 302
force = true

[[redirects]]
from = "/*"
to = "/"
status = 200

[[headers]]
for = "/*"
[headers.values]
Link = "</sitemap.xml>; rel=\"sitemap\""

[[plugins]]
package = "netlify-plugin-debug-cache"
