# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
base = "/"
publish = "dist/"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

# let's test this
# [build.processing]
# bundle = true
# minify = true

[[redirects]]
from = "/*"
to = "/"
status = 200

[[plugins]]
package = "netlify-plugin-debug-cache"
