name: Build

on:
  push:
    branches:
      - master
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Node.js 14
        uses: actions/setup-node@v1  # Set up Node.js with a specified version
        with:
          node-version: '14'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build